backend/dissemination/urls.py
from django.urls import path

from dissemination import views

app_name = "dissemination"

urlpatterns = [
    path(
        "workbook/xlsx/<str:file_type>/<str:report_id>",
        views.XlsxDownloadView.as_view(),
        name="XlsxDownload",
    ),
    path(
        "report/pdf/<str:report_id>",
        views.PdfDownloadView.as_view(),
        name="PdfDownload",
    ),
    path(
        "report/pdf/ota/<str:uuid>",
        views.OneTimeAccessDownloadView.as_view(),
        name="OtaPdfDownload",
    ),
    path(
        "summary-report/xlsx/<str:report_id>",
        views.SingleSummaryReportDownloadView.as_view(),
        name="SummaryReportDownload",
    ),
    path(
        "summary-report/xlsx",
        views.MultipleSummaryReportDownloadView.as_view(),
        name="MultipleSummaryReportDownload",
    ),
    path("search/", views.Search.as_view(), name="Search"),
    path("search/advanced/", views.AdvancedSearch.as_view(), name="AdvancedSearch"),
    path("summary/<str:report_id>", views.AuditSummaryView.as_view(), name="Summary"),
]

backend/templates/audit-metadata.html
<!-- Audit metadata. Included at the bottom of several screens. -->
<div class="audit-metadata">
    <div class="grid-container">
        <dl class="grid-row grid-gap">
            <div class="tablet:grid-col-6">
                <dt>
                    Entity name
                </dt>
                <dd>
                    {{ auditee_name | default_if_none:'' }}
                </dd>
            </div>
            <div class="tablet:grid-col-6">
                <dt>
                    Report ID
                </dt>
                <dd>
                    #{{ report_id | default_if_none:'' }}
                </dd>
            </div>
            <div class="tablet:grid-col-6">
                <dt>
                    UEI
                </dt>
                <dd>
                    {{ auditee_uei | default_if_none:'' }}
                </dd>
            </div>
        </dl>
    </div>
</div>

backend/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="home margin-bottom-4">
    <div class="grid-container">
      {# Title #}
      <h1 class="font-sans-3xl text-primary-darker">
          <span class="text-heavy">
              The Federal Audit Clearinghouse (FAC)
          </span>
          <span class="text-semibold">
              is the place to submit and review federal grant audits.
          </span>
      </h1>
  
      <hr />
  
      {# Cards #}
      <ul class="usa-list usa-list--unstyled width-full margin-top-4">
          <li class="usa-card">
              <div class="usa-card__container radius-0 border-2px border-base-light">
                  <div class="usa-card__header border-bottom-2px border-base-light bg-accent-cool-lighter padding-y-105">
                      <h2 class="usa-card__heading font-sans-2xl text-primary-darker text-bold">I want to</h2>
                  </div>
                  <div class="usa-card__body bg-base-lightest margin-0">
                      <ul class="usa-card-group display-flex desktop:flex-row flex-justify">
                          <li class="usa-card grid-col flex-fill padding-top-4 padding-bottom-2">
                              <div class="usa-card__container home-image submission shadow-1">
                                  <a class="usa-link text-white font-sans-2xl margin-0 text-semibold display-flex flex-column flex-align-center"
                                      href="/openid/login/"
                                      aria-controls="login-modal"
                                      data-open-modal >
                                      <p class="font-sans-2xl margin-0 display-block">Submit</p>
                                      <p class="font-sans-xl margin-0">an audit</p>
                                  </a>
                              </div>
                          </li>
                          <p class="font-sans-2xl text-primary-darker text-semibold margin-x-4 margin-y-0 flex-align-self-center">or</p>
                          <li class="usa-card grid-col flex-fill padding-top-4 padding-bottom-2">
                              <div class="usa-card__container home-image searching shadow-1">
                                  <a class="usa-link text-white font-sans-2xl margin-0 text-semibold display-flex flex-column flex-align-center"
                                      href="{% url 'dissemination:Search' %}"
                                      target="_blank">
                                      <p class="font-sans-2xl margin-0 display-block">Search</p>
                                      <p class="font-sans-xl margin-0">for audits</p>
                                  </a>
                              </div>
                          </li>
                      </ul>
                  </div>
              </div>
          </li>
      </ul>
    </div>
  </div>
{% endblock content %}